Remove squashfs-based compression.
Letting the system decompress itself at 1st boot
causes more complexity and more writes on the device.
Therefore this commit removes this and provides an
image with the system uncompressed on its root
partition.
For distribution the image may still be compressed
efficiently using gzip or xz.

diff --git a/scripts/create-image/functions b/scripts/create-image/functions
--- a/scripts/create-image/functions
+++ b/scripts/create-image/functions
@@ -132,6 +132,21 @@ check_fs_hierarchy()
     return $result
 }
 
+finalize_fs()
+{
+    fs_tree=$(cd $1; pwd)
+    cd $fs_tree
+
+    # clean up
+    rm -rf proc/* sys/* dev/* tmp/* \
+            $(find run -type f) /var/cache/* /var/lock
+
+    # move the existing init
+    mv sbin/init sbin/init.orig
+    cd sbin
+    ln -s ../opt/debootstick/live/init/first-init.sh init
+}
+
 # failsafe mode handling
 # ----------------------
 # we want to leave the system in a clean state,
@@ -165,7 +180,7 @@ on_exit()
 
     # get args
     toplevel=0
-    if [ "$1" == "--toplevel" ]
+    if [ "$1" = "--toplevel" ]
     then
         toplevel=1
         shift
@@ -177,6 +192,7 @@ on_exit()
     then
         echo
         echo "E: an error occured."
+        echo "starting sh"; sh
         echo -n "I: restoring a clean state... "
         undo_all
         echo "done"
@@ -360,49 +376,6 @@ f_with()
 
 # verbosity reduction
 # -------------------
-io_unbuffered_mksquashfs()
-{
-    echo 1 > $mksquashfs_result_file	# default value
-    script -q \
-        -c "mksquashfs $* && echo 0 > $mksquashfs_result_file" \
-        /dev/null
-}
-
-io_unbuffered_tr()
-{
-    stdbuf -i0 -o0 -e0 tr $*
-}
-
-io_unbuffered_grep()
-{
-    stdbuf -i0 -o0 -e0 grep $*
-}
-
-quiet_mksquashfs()
-{
-    task_name=$1
-    shift
-
-    mksquashfs_result_file=$(mktemp)
-
-    io_unbuffered_mksquashfs $* | io_unbuffered_tr '\n[' '&\n'              \
-                                | io_unbuffered_grep -oE "[0-9]+/[0-9]+"    \
-                                | while read ratio
-                                  do
-                                        echo -en "I: $task_name... $((100*$ratio))%\r"
-                                  done
-    mksquashfs_return_value=$(cat $mksquashfs_result_file)
-    rm $mksquashfs_result_file
-
-    if [ "$mksquashfs_return_value" = "0" ]
-    then
-        echo -e "I: $task_name... done"
-    else
-        echo -e "I: $task_name... failed"
-    fi
-    return $mksquashfs_return_value
-}
-
 quiet_grub_install()
 {
     device=$1
@@ -419,7 +392,7 @@ quiet_grub_install()
                 grep -v "Installing"        | \
                 grep -v "Generating"        | \
                 grep -v "Found .* image:"   | \
-                grep -vx "done" 1>&2        || true
+                grep -v "^done$" 1>&2        || true
 
     # grep returns non-zero if no line is found.
     # in our case, having no error line is a good
@@ -547,65 +520,6 @@ EOF
     undo mount $image_lvroot_device $image_lvroot_mountpoint
     undo kpartx -a $image_device
     undo losetup $image_device "$image_file"
-}
-
-# system compression
-# ------------------
-make_compressed_fs()
-{
-    # these operations (up to the squashfs compression below)
-    # should be fast: we are just removing or moving files
-    # in the same filesystem
-
-    fs_tree=$(cd $1; pwd)
-
-    # we will work with two subdirectories,
-    # '.fs.orig' & 'compressed'
-    cd $fs_tree
-    contents=$(ls -A)
-    mkdir .fs.orig .fs.compressed
-    mv $contents .fs.orig/
-
-    cd .fs.orig
-
-    # clean up
-    rm -rf proc/* sys/* dev/* tmp/* run/* /var/cache/*
-
-    # some files should be available early at boot
-    # (thus not compressed in the squashfs image)
-    while read f
-    do
-        mkdir -p $(dirname $fs_tree/.fs.compressed/$f)
-        mv $f $fs_tree/.fs.compressed/$f
-    done << EOF
-boot
-bin/busybox
-opt/debootstick/live/init/first-init.sh
-$(find lib -name squashfs.ko -o -name loop.ko)
-EOF
-
-    # move the init
-    mv sbin/init sbin/init.orig
-
-    # create compressed image
-    quiet_mksquashfs "draft image - compressing (squashfs)" \
-            $PWD $fs_tree/.fs.compressed/fs.squashfs $MKSQUASHFS_OPTS
-
-    # the following operations should also be fast.
-
-    # finalize compressed tree
-    cd $fs_tree/.fs.compressed
-    mkdir -p sbin proc sys tmp/os tmp/os_rw tmp/os_ro dev
-    cd sbin
-    ln -s ../opt/debootstick/live/init/first-init.sh init
-    cd ../bin
-    ln -s busybox sh
-
-    # keep only the compressed version in fs_tree
-    cd $fs_tree/.fs.compressed
-    mv $(ls -A) ..
-    cd ..
-    rm -rf .fs.orig .fs.compressed
 }
 
 # UEFI support
