Minor update to error message style

diff --git a/scripts/create-image/os-detect b/scripts/create-image/os-detect
--- a/scripts/create-image/os-detect
+++ b/scripts/create-image/os-detect
@@ -11,7 +11,7 @@ check_fs_hierarchy()
         if [ ! -f "$fs_tree/bin/echo" ]
         then
             echo "E: No /bin/echo found in $fs_tree."
-            echo "E: This does not seem to be a chroot environment."
+            echo "E: This does not seem to be a valid chroot environment. Aborting."
             return 1
         fi
 
@@ -26,14 +26,14 @@ check_fs_hierarchy()
         if [ "$ID" != "debian" -a "$ID_LIKE" != "debian" ]
         then
             echo "E: /etc/os-release file in $fs_tree does not report a debian-like OS."
-            echo "E: debootstick currently cannot handle such a chroot environment." >&2
-            echo "E: Run 'debootstick --help-os-support' for more info."
+            echo "E: This chroot environment is not supported by debootstick.  Aborting." >&2
+            echo "E: Run 'debootstick --help-os-support' for a list of supported chroot environments."
             return 1
         fi
         ;;
     "2")
         chroot "$fs_tree" echo -n >/dev/null 2>&1 || {
-            echo "E: Unable to execute binaries (/bin/echo at least) in the chroot environment."
+            echo "E: Unable to execute binaries (/bin/echo at least) in the chroot environment. Aborting."
             echo "E: Please verify:"
             echo "E: - file permissions in the chroot environment"
             echo "E: - that your host CPU is able to run binaries of the target architecture"
@@ -42,7 +42,7 @@ check_fs_hierarchy()
         }
         chroot "$fs_tree" which apt-get >/dev/null 2>&1 || {
             echo "E: No apt-get found in $1."
-            echo "E: debootstick cannot handle this kind of chroot environment."
+            echo "E: This chroot environment is not supported by debootstick.  Aborting."
             echo "E: Run 'debootstick --help-os-support' for more info."
             return 1
         }
@@ -61,6 +61,6 @@ detect_target_type()
             return
         }
     done
-    echo "E: debootstick does not know how to handle your chroot environment." >&2
-    echo "E: Run 'debootstick --help-os-support' for more info." >&2
+    echo "E: This chroot environment is not supported by debootstick.  Aborting." >&2
+    echo "E: Run 'debootstick --help-os-support' for a list of supported chroot environments." >&2
 }
