New option "--sector-size"
This allows to generate an image to be flashed on a disk
with non-default logical sector size. Default is 512 bytes.

Important note: when using the "--system-type installer" option,
whichever will be the target disk sector size after migrating,
you should probably use the default 512-bytes sector size.
The reason for this is that you will flash the image on a USB
device first, and this device probably expects a 512-bytes sector
size.

This option should only be used if you want to flash the image
directly on a 4Kn disk for instance.

diff --git a/scripts/create-image/common/failsafe b/scripts/create-image/common/failsafe
--- a/scripts/create-image/common/failsafe
+++ b/scripts/create-image/common/failsafe
@@ -169,8 +169,8 @@ undo_mkdir()
 
 undo_losetup()
 {   # we assume the failsafe command was
-    # $ failsafe losetup <loop_device> <file>
-    losetup -d "$1"
+    # $ failsafe losetup --sector-size <sector-size> <loop_device> <file>
+    losetup -d "$3"
 }
 
 undo_partx()
@@ -214,6 +214,19 @@ undo_chroot()
 failsafe()
 {
     $* &&  echo "$*" >> $FAILSAFE_COMMANDS
+}
+
+# workaround the fact losetup sometimes fail with
+# 'resource temporarily unavailable' error.
+# (sometimes seen when using "--sector-size 4096" option)
+failsafe_losetup()
+{
+    while [ 1 ]
+    do
+        losetup "$@" 2>/dev/null && break || true
+        sleep 0.1   # retry after a short delay
+    done
+    echo losetup "$@" >> $FAILSAFE_COMMANDS
 }
 
 undo()
